image: python:3.7

pipelines:
  default:
    - step:
        name: pytest
        image: python:3.7
        script:
          - pip install poetry
          - poetry install
          - poetry run pytest
        caches:
          - pip
          - poetry
definitions:
  caches:
    poetry: ~/.cache/pypoetry/cache
